/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stack.niall;

import java.awt.Color;
import static jdk.nashorn.internal.objects.NativeMath.round;

/**
 *
 * @author t00174406
 */
public class FormulaUI extends javax.swing.JFrame {

    /**
     * Creates new form FormulaUI
     */
    public FormulaUI() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TriAreaPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        taBaseTxt = new javax.swing.JTextField();
        taHeightTxt = new javax.swing.JTextField();
        taBtn = new javax.swing.JButton();
        taAnswerTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CirAreaPnl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        caRadiusTxt = new javax.swing.JTextField();
        acBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        caAnswerTxt = new javax.swing.JTextField();
        RecAreaPnl = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        raLengthTxt = new javax.swing.JTextField();
        raWidthTxt = new javax.swing.JTextField();
        arAnswerBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        raAnswerTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        paBaseTxt = new javax.swing.JTextField();
        paHeightTxt = new javax.swing.JTextField();
        apAnswerBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        paAnswerTxt = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        TriAreaPnl.setBackground(new java.awt.Color(0, 102, 102));
        TriAreaPnl.setPreferredSize(new java.awt.Dimension(250, 154));

        jLabel1.setText("Area of Triangle");

        jLabel2.setText("Base");

        jLabel3.setText("Height");

        taHeightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taHeightTxtActionPerformed(evt);
            }
        });

        taBtn.setLabel("=");
        taBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBtnActionPerformed(evt);
            }
        });

        taAnswerTxt.setEditable(false);

        jLabel4.setText("Answer");

        javax.swing.GroupLayout TriAreaPnlLayout = new javax.swing.GroupLayout(TriAreaPnl);
        TriAreaPnl.setLayout(TriAreaPnlLayout);
        TriAreaPnlLayout.setHorizontalGroup(
            TriAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TriAreaPnlLayout.createSequentialGroup()
                .addGroup(TriAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TriAreaPnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(TriAreaPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(taBaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(TriAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TriAreaPnlLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addGroup(TriAreaPnlLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(TriAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TriAreaPnlLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addGroup(TriAreaPnlLayout.createSequentialGroup()
                                .addGroup(TriAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(taAnswerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(taHeightTxt))
                                .addGap(39, 39, 39)
                                .addComponent(taBtn))))
                    .addGroup(TriAreaPnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        TriAreaPnlLayout.setVerticalGroup(
            TriAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TriAreaPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(TriAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TriAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taBaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taHeightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CirAreaPnl.setBackground(new java.awt.Color(255, 255, 51));

        jLabel5.setText("Area of Circle");

        jLabel6.setText("Radius");

        caRadiusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caRadiusTxtActionPerformed(evt);
            }
        });

        acBtn.setText("=");
        acBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Answer");

        caAnswerTxt.setEditable(false);

        javax.swing.GroupLayout CirAreaPnlLayout = new javax.swing.GroupLayout(CirAreaPnl);
        CirAreaPnl.setLayout(CirAreaPnlLayout);
        CirAreaPnlLayout.setHorizontalGroup(
            CirAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CirAreaPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(CirAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CirAreaPnlLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CirAreaPnlLayout.createSequentialGroup()
                        .addGroup(CirAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(caAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CirAreaPnlLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7)))
                        .addGap(98, 98, 98))))
            .addGroup(CirAreaPnlLayout.createSequentialGroup()
                .addGroup(CirAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CirAreaPnlLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(caRadiusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(acBtn))
                    .addGroup(CirAreaPnlLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        CirAreaPnlLayout.setVerticalGroup(
            CirAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CirAreaPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CirAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acBtn)
                    .addComponent(caRadiusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        RecAreaPnl.setBackground(new java.awt.Color(255, 0, 0));
        RecAreaPnl.setPreferredSize(new java.awt.Dimension(250, 154));

        jLabel8.setText("Area of Rectangle");

        jLabel9.setText("Length");

        jLabel10.setText("Width");

        raWidthTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raWidthTxtActionPerformed(evt);
            }
        });

        arAnswerBtn.setText("=");
        arAnswerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arAnswerBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Answer");

        raAnswerTxt.setEditable(false);

        javax.swing.GroupLayout RecAreaPnlLayout = new javax.swing.GroupLayout(RecAreaPnl);
        RecAreaPnl.setLayout(RecAreaPnlLayout);
        RecAreaPnlLayout.setHorizontalGroup(
            RecAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecAreaPnlLayout.createSequentialGroup()
                .addGroup(RecAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecAreaPnlLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel10))
                    .addGroup(RecAreaPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(raLengthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(RecAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(RecAreaPnlLayout.createSequentialGroup()
                                .addComponent(raWidthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(arAnswerBtn))))
                    .addGroup(RecAreaPnlLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(RecAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(raAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        RecAreaPnlLayout.setVerticalGroup(
            RecAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecAreaPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RecAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RecAreaPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raLengthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raWidthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arAnswerBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(raAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 154));

        jLabel12.setText("Area of Parallelogram ");

        jLabel13.setText("Base");

        jLabel14.setText("Height");

        apAnswerBtn.setText("=");
        apAnswerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apAnswerBtnActionPerformed(evt);
            }
        });

        jLabel15.setText("Answer");

        paAnswerTxt.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel13)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(paBaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(paHeightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(paAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(apAnswerBtn)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paBaseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paHeightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apAnswerBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paAnswerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TriAreaPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CirAreaPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(RecAreaPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 715, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TriAreaPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CirAreaPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RecAreaPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taHeightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taHeightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taHeightTxtActionPerformed

    private void raWidthTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raWidthTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raWidthTxtActionPerformed

    private void taBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBtnActionPerformed
        String heightAsString = taHeightTxt.getText();
        String baseAsString = taBaseTxt.getText();
        
        double height = Double.parseDouble(heightAsString);
        double base = Double.parseDouble(baseAsString);     
        double answer = Areas.Triangle(base, height);
        double roundOff = (double) Math.round(answer * 100) / 100;
        
        taAnswerTxt.setText(Double.toString(roundOff));
        
    }//GEN-LAST:event_taBtnActionPerformed

    private void acBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acBtnActionPerformed
        String radiusAsString = caRadiusTxt.getText();
        
        double radius = Double.parseDouble(radiusAsString);
        double answer = Areas.Circle(radius);
        double roundOff = (double) Math.round(answer * 100) / 100;
        
        caAnswerTxt.setText(Double.toString(roundOff));
        
    }//GEN-LAST:event_acBtnActionPerformed

    private void caRadiusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caRadiusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caRadiusTxtActionPerformed

    private void arAnswerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arAnswerBtnActionPerformed
        String widthAsString = raWidthTxt.getText();
        String lengthAsString = raLengthTxt.getText();
        
        double width = Double.parseDouble(widthAsString);
        double length = Double.parseDouble(lengthAsString);     
        double answer = Areas.Rectangle(length, width);
        double roundOff = (double) Math.round(answer * 100) / 100;
        
        raAnswerTxt.setText(Double.toString(roundOff));
    }//GEN-LAST:event_arAnswerBtnActionPerformed

    private void apAnswerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apAnswerBtnActionPerformed
        String heightAsString = paHeightTxt.getText();
        String baseAsString = paBaseTxt.getText();
        
        double height = Double.parseDouble(heightAsString);
        double base = Double.parseDouble(baseAsString);     
        double answer = Areas.Parallelogram(base, height);
        double roundOff = (double) Math.round(answer * 100) / 100;
        
        paAnswerTxt.setText(Double.toString(roundOff));
    }//GEN-LAST:event_apAnswerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CirAreaPnl;
    private javax.swing.JPanel RecAreaPnl;
    private javax.swing.JPanel TriAreaPnl;
    private javax.swing.JButton acBtn;
    private javax.swing.JButton apAnswerBtn;
    private javax.swing.JButton arAnswerBtn;
    private javax.swing.JTextField caAnswerTxt;
    private javax.swing.JTextField caRadiusTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField paAnswerTxt;
    private javax.swing.JTextField paBaseTxt;
    private javax.swing.JTextField paHeightTxt;
    private javax.swing.JTextField raAnswerTxt;
    private javax.swing.JTextField raLengthTxt;
    private javax.swing.JTextField raWidthTxt;
    private javax.swing.JTextField taAnswerTxt;
    private javax.swing.JTextField taBaseTxt;
    private javax.swing.JButton taBtn;
    private javax.swing.JTextField taHeightTxt;
    // End of variables declaration//GEN-END:variables
}
